####  PBS preamble
#PBS -N Bessy
#PBS -M tpr@hi.is
#PBS -m abe

#PBS -l nodes=1:ppn=8
### #PBS -l gres=gurobi:1
#PBS -j oe
#PBS -V

#PBS -A Messy_Bessy
#PBS -l qos=short
#PBS -q short

####  End PBS preamble
#  Print the assigned nodes
if [ "x${PBS_NODEFILE}" != "x" ] ; then
   cat $PBS_NODEFILE   # print the CPUs when running with PBS
fi

# Change to the PBS working directory
cd $PBS_O_WORKDIR

#  Put your job commands after this line
gurobi_cl ResultFile=Bessy.sol TimeLimit=100 ./Bessy.lp
